// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package enterprise.domain;

import enterprise.domain.PlantHireRequestPlant;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PlantHireRequestPlant_Roo_Configurable {
    
    declare @type: PlantHireRequestPlant: @Configurable;
    
}
